import Head from 'next/head';
import styles from '../styles/Login.module.scss';

// MUI
import { Container } from '@mui/system';
import { TextField, Button } from '@mui/material';

export default function Home() {
  return (
    <Container className={styles['login__container']} maxWidth='xl'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {/* email */}
        <TextField
          required
          className='login__input--email'
          label='Email'
          variant='outlined'
        />

        {/* password */}
        <TextField
          id='login__input--password'
          className='login__input--password'
          label='Password'
          type='password'
          variant='outlined'
        />
        {/* login */}
        <Button variant='contained'>Login</Button>
        {/* sign up */}
        <Button variant='outlined'>Sign Up</Button>
      </main>
    </Container>
  );
}
