import Head from 'next/head';

// MUI
import { blue } from '@mui/material/colors';
import { TextField, Button } from '@mui/material';

// Icons
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faListCheck } from '@fortawesome/free-solid-svg-icons';

// React
import { useEffect } from 'react';

export default function Home() {
  // Set MUI variables
  useEffect(() => {
    document.documentElement.style.setProperty('--login-main-border-color', blue[400]);
    document.documentElement.style.setProperty('--login-main-icon-color', blue[700]);
  }, []);

  return (
    <div className='login login__container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='login__main'>
        <div className='login__main--icon'>
          <FontAwesomeIcon icon={faListCheck} />
        </div>

        <form action='' className='form__container'>
          {/* email */}
          <TextField
            required
            className='login__input--email'
            label='Email'
            variant='outlined'
          />

          {/* password */}
          <TextField
            id='login__input--password'
            className='login__input--password'
            label='Password'
            type='password'
            variant='outlined'
          />

          <div className='form__actions'>
            {/* login */}
            <Button className='form__actions--button' variant='contained'>Login</Button>
            {/* sign up */}
            <Button className='form__actions--button' variant='outlined'>Sign Up</Button>
          </div>
        </form>
      </main>
    </div>
  );
}
