import Head from 'next/head';

// Redux
import { login, logout } from '/utils/store/auth/authSlice';
import { useDispatch, useSelector } from 'react-redux';

// MUI
import { blue } from '@mui/material/colors';
import { TextField, Button } from '@mui/material';

// Icons
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faListCheck } from '@fortawesome/free-solid-svg-icons';

// React
import { useEffect } from 'react';

// Routing
import { useRouter } from 'next/router';

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  const isLoggedIn = useSelector((state) => state.auth.isLoggedIn);

  // Protect this route
  useEffect(() => {
    if (!isLoggedIn) {
      router.push('/login');
    }
  }, [isLoggedIn]);

  // Set MUI variables
  useEffect(() => {
    document.documentElement.style.setProperty(
      '--login-main-border-color',
      blue[400]
    );
    document.documentElement.style.setProperty(
      '--login-main-icon-color',
      blue[700]
    );
  }, []);

  return (
    <div className='login login__container'>
      <Head>
        <title>Home - TaskPlanner</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Home</h1>

      <button
        onClick={() => {
          isLoggedIn ? dispatch(logout()) : dispatch(login());
        }}
      >
        {isLoggedIn ? 'LOGOUT' : 'LOGIN'}
      </button>
    </div>
  );
}
